### ISSUE TITLE
Negative width/height/length values are confusing

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#12]
Seems odd that something could have a "negative" dimensional value. Is this necessary?

**Comment by arthursw** [comment]
I think it's sometimes useful (to create hollow shapes) and I think the problem is more that currently I don't render the back of the faces. There should be a transparent material for the back of the faces.
This is in my todo list.

**Comment by gabrielw-us** [comment]
1) True, this could be useful when directly typing numbers. Normally I just use the "Flip Normals" tool in PB-Unity, but negative numbers could work also.

2) However, when dragging out a shape, I think it would be best to always stay "positive". Otherwise, we must require users to drag in a specific direction: for example, dragging "left" might create a hollow shape, and "right" would create a solid shape. This would be confusing and often not desired. What do you think?

3) Maybe it would be best to just have a "Hollow" checkbox on the Shape Creation panel? Or, in addition to the negative numbers. I think that would work well.

_Note: Created an official "Feature Request" for the backfaces ( #12 )_

**Comment by arthursw** [comment]
Well, I copied the very nice 3Ds Max shape creation system. The great thing is that is creates shapes where you want, with the dimensions you want. If there is something imperfect in my solution, it's probably because I didn't manage to reproduce the 3Ds max method.

I'll recheck if I can improve the shape creation and develop this answer.

A "Hollow" Checkbox would be great, let's make it a feature request. Maybe there are two checkboes: 

- "Invert" just to flip normal, 
- "Hollow" to create two shapes: a normal one and an inverted one inside.

**Comment by gabrielw-us** [comment]
Most important, to me, is being consistent. I worry about this:

1) User specifies a box size "-10, 20, -15". When they click, a hollow shape of that size appears.
2) Another time, user hand-drags a box to size "-10, 20, -15. This time though, it creates a solid box.

So, the same values could lead to different results, which confuses users. It would be better to be 100% consistant and either:

a) When either dragging or typing, a negative value will create a hollow box, always
b) When either dragging or typing, a negative value will never create a hollow box

Option "A" becomes a problem, since it will further confuse users if they drag one way, then another, the shape will go from solid to hollow. This is technically "consistent", but visually confusing.

Option "B" is better, because it is both technically and visually consistent.

So, I prefer Option B, with a checkbox option for "Inverted".

About the "Hollow" option, sure, good plan. However, any major new features that don't fix current issues, will have to wait till after we've been on the marketplace for at least a month.

**Comment by arthursw** [comment]
Yes, Option B is acutally how 3Ds max work. Perfect.

**Comment by arthursw** [comment]
fixed!
