### ISSUE TITLE
Mouse events not fully consumed after creating a shape, and editing it's shape

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#121]
After shape is created, mouse click/drag stops being fully consumed, and cam will move when dragging faces to adjust size (still in Create Shape Mode).

(using UE Nav)

![cam-move](https://cloud.githubusercontent.com/assets/5855470/22309511/8bc1ef9c-e319-11e6-8a77-4dbd9688467f.gif)

**Comment by gabrielw-us** [comment]
Re-assigning to "Future Tasks - middle term" since the relevant feature isn't for AV2

**Comment by arthursw** [comment]
Fixed
