### ISSUE TITLE
Capsule shape "stealing" edits from other shapes sizer-box

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#122]
Sorry, hard to describe, feel free to re-title this. Easy to repro though

1. Create new Cube
1. Create new Capsule
1. Notice blue shape-sizer-box remains on the Cube
1. Edit the blue shape-sizer-box : capsule is edited, not the cube, and size fluctuates badly

Assigning "Future Tasks - Middle Term" since the relevant feature isn't going to be part of AV2)

![image](https://cloud.githubusercontent.com/assets/5855470/22309791/c866c674-e31a-11e6-9525-4c62d2e99c82.png)

**Comment by arthursw** [comment]
Fixed.
