### ISSUE TITLE
Sizer box (name for that?) not updating to match direct value input on Shape

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#123]
1. Create Cube
1. Move to Select and Transform mode, with Cube selected
1. Use the Shape Parameters to edit the Cube
1. Notice the blue "sizer box" does not change with the shape

Not important till after AV2, or whenever we start fully implementing this feature.

![image](https://cloud.githubusercontent.com/assets/5855470/22309930/6150b21e-e31b-11e6-98ee-e6842efb475b.png)

**Comment by arthursw** [comment]
Fixed
