### ISSUE TITLE
"Create Shape" can be accidentally activated outside of Shape Mode

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#124]
1. Create new Cube
1. Switch to Select and Transform
1. With Cube selected, look at the Shape parameters area, and use the drop-down to select different shape type
1. Click and drag- shape is created, despite being in Select and Transform mode

I think there might be room to merge these modes, make it more seamless...but let's keep it simple and separate for now.

I think the solution in this case, would be removing the "Shape Type" drop down menu when not in Create mode.

**Comment by arthursw** [comment]
Ok, changing the dropdown list does not force to shape mode anymore, and re-generates the shape. This is good enough for me, I just hope it won't be a problem for the undo-redo stack. It should be ok, but I'll investigate this later.

**Comment by gabrielw-us** [comment]
Does the dropdown need to show? Maybe just remove it? Seems likely to cause trouble, and uses up UI space.

**Comment by arthursw** [comment]
I like being able to change the shape type. If we are able to change it's dimensions, why not its type? It makes more sens to have full control, in my opinion.

**Comment by gabrielw-us** [comment]
Sure, that makes sense. Especially if it could retain basic dimensions (ie, going from Box to Cylinder could keep width (radius) and height).
