### ISSUE TITLE
Vertices aren't shown until selected

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#126]
1. Create new Cube
1. Move to Vert mode- no verts are shown
1. Drag select verts- now I can see the selected ones, but no others

**Comment by arthursw** [comment]
Fixed.

Note: vertices show only in vertex mode. Should I change that?

**Comment by gabrielw-us** [comment]
Hmm, I think it's fine for now, but if we do implement a "multi-element editing" mode, then we'd change that. Something for after AV2 though.

**Comment by arthursw** [comment]
No that would not change my question.

My questions are: 
Should we show vertices only when vertex mode is activated?
Should we show edges only when edge mode is activated?

Disregarding the fact that object, face, edge and vertex mode can be all activated at the same time.

**Comment by gabrielw-us** [comment]
Oh, I see. Personally, I'd prefer to only show the active element. Much cleaner visually.

Also, if we show verts, but they are not selectable until moving to vert mode, that will confuse people.
