### ISSUE TITLE
Unable to drag-select elements while using UE Nav Mode

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#127]
1. Create Cube
1. Move to Vert, Edge, or Face mode
1. Turn on "UE Nav Mode"
1. Attempt to drag-select any elements (holding ALT + CTRL, of course) - drag box shows, but nothing is selected
1. Turn "UE Nav Mode" off - now drag select works properly

**Comment by gabrielw-us** [comment]
Note: this does work if also holding SHIFT. Interesting, might help debug?

**Comment by arthursw** [comment]
Ok, I'm on my way to fix this.

**Comment by arthursw** [comment]
Fixed.
