### ISSUE TITLE
Scaling multiple verts down to single location can break geometry

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#128]
1. New Cube
1. Vert mode
1. Select two verts
1. Scale verts until they are at same world position

Geometry now shows holes (image below)

Warnings shown in JS console:
`LogTemp: Warning: Triangulating.
LogTemp: Warning: Cannot be triangulated.
LogTemp: Warning: Triangulating.
LogTemp: Warning: Cannot be triangulated.`
![image](https://cloud.githubusercontent.com/assets/5855470/22310594/bcca619c-e31d-11e6-9a19-68e76b791e99.png)

**Comment by arthursw** [comment]
This is kind of normal. 

The face cannot be triangulated because two of its vertices have the same location. That is why ProBuilder don't render it. 

We can add a warning message when two vertices are at the same location, saying something like 'Try to weld vertices to create valid geometry'. 

We could also auto-weld vertices if they get too close to each other.

**Comment by arthursw** [comment]
Notice that if you scale up again the vertices (to separate them) the face gets rendered again.

**Comment by gabrielw-us** [comment]
How about just merging verts when the mouse button is released? I still see it as a bug, and I believe other users will also, if faces disappear suddenly.

**Comment by arthursw** [comment]
Yes, or maybe it's possible to keep the face, I'll check that.

**Comment by gabrielw-us** [comment]
I'd say, merge the verts and make the face a tri...but maybe that's what you mean? :)

**Comment by gabrielw-us** [comment]
Note: same thing happens with edges placed onto another (faces disappear).

This might be a non-AV2 thing?

**Comment by arthursw** [comment]
Faces are not broken into triangles (when necessary) when collapsing vertices. So this should be fixed :)
