### ISSUE TITLE
Unable to undo Shift-Extrude (or GUI Extrude) action

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#129]
1. Create Cube
1. Face mode, select a face, shift-extrude it
1. Attempt Undo- does not work.

UPDATE: unable undo after GUI-validate-extrude, either. However, the errors did not show up?

Console errors:
`Error: d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:606: TypeError: Cannot read property '3' of undefined
Error: TypeError: Cannot read property '3' of undefined
Error:     at AddEdgeToFaceCommand.RemoveEdge (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:606:56)
Error:     at AddEdgeToFaceCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:622:14)
Error:     at ExtrudeCommand.ExecuteAtomicCommand (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:70:16)
Error:     at ExtrudeCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:91:22)
Error:     at ExtrudeCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\ExtrudeCommand.js:175:15)
Error:     at ExtrudeCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:101:14)
Error:     at CommandManager.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:118:26)
Error:     at CommandManager.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:138:22)
Error:     at ProBuilder_C0.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\ProBuilder.js:572:29)`

**Comment by arthursw** [comment]
Fixed.

**Comment by arthursw** [comment]
There will probably be other Undo/Redo errors though...
