### ISSUE TITLE
Unable to reset project via the old "edit script" method?

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#130]
I'm editing the script "extension-ProBuilder" in "Plugins\ProBuilder\Content\Scripts", but the project doesn't reset.

Do I have the wrong file?

**Comment by arthursw** [comment]
The script to edit is in "Content/Scripts", not "Plugins/ProBuilder/Content/Scripts" :-)
