### ISSUE TITLE
"Sizing box" - disable or complete for Alpha V2?

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#131]
I've noticed the new "sizing box" that was added recently, this is a nice feature, but has several bugs and only seems to work on basic shapes, currently.

I propose we disable this for the upcoming Alpha V2 milestone, so it doesn't push that back. What do you think?

**Comment by arthursw** [comment]
yes I'm not happy with this now, I only worked a few hours on this, and it's not very useful for now.
