### ISSUE TITLE
Unable to Undo after scaling face

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#133]
1. New Cube
1. Face Mode > Select Face
1. Scale face inward/outward on any or all axis
1. Attempt extrude- does not work.

I didn't see any errors in the console the second time I tested this, and had already cleared old console logs.

**Comment by arthursw** [comment]
Fixed (very likely same bug as extrude undo/redo).
