### ISSUE TITLE
After creating a new Shape, and moving to "Select and Transform" mode, sizing box still visible but not active

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#136]
1. New cube
1. Move to "Select and Transform" mode
1. Notice blue sizing box is still shown- but cannot be used

![image](https://cloud.githubusercontent.com/assets/5855470/22313750/328a2418-e32c-11e6-99c3-c8c00a21e32b.png)

**Comment by arthursw** [comment]
Fixed.
