### ISSUE TITLE
What is the purpose of "Create Holes" in Extrude Settings?

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#138]

**Comment by arthursw** [comment]
This is very nice:

![janv -27-2017 13-14-39](https://cloud.githubusercontent.com/assets/1814799/22370622/a93c3e0e-e492-11e6-900e-f43dd53ed5d5.gif)

**Comment by gabrielw-us** [comment]
Does it require that the faces align, to create that hole? I was guessing it did something like this, but wasn't sure...

Very nice indeed!
