### ISSUE TITLE
What is "Snap to Parallel Faces" in Extrude Settings?

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#139]

**Comment by arthursw** [comment]
When you extrude, it will snap to the other faces which are parallel (and on the same mesh). 

This is to enable 'Create Holes' when extruding a face onto another one when they are not aligned on the grid, or when the grid snap is disabled.

Improvement: could provide a slider to choose the snap distance.

**Comment by gabrielw-us** [comment]
Ahh ok, very nice :)
