### ISSUE TITLE
After moving a PB object, then Undo, green outline (collision?) left behind

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#14]
1) Create  new PB shape
2) Switch to "Select and Transform" Mode
3) Move the shape in any direction
4) Undo- note the green outline (collision, I'm guessing?) is left behind, not updated

![image](https://cloud.githubusercontent.com/assets/5855470/20065886/c0abb3ca-a4dd-11e6-8f09-729ecd05ee20.png)

**Comment by arthursw** [comment]
Yes, I know this kind of bug, I spent some time last week trying to render mesh outlines differently, it should be fixed soon.
