### ISSUE TITLE
What is "Mesh Group" in Extrude/Face Settings?

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#140]

**Comment by arthursw** [comment]
Mesh Group is not part of the Extrude setting (it will be more clear when I will improve the GUI).

"Mesh group" is used to create mesh groups, which is useful to apply different textures on the same mesh, as I explained [here](https://github.com/gabrielw-us/ProBuilder-Unreal-Public-Tracker/issues/73#issuecomment-270376673).

**Comment by gabrielw-us** [comment]
Oh, ok- "Submesh" is the term I'm used to. Both are fine :)
