### ISSUE TITLE
Suggestion: Replace "Offset" with "Inset", and only allow negative amount

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#141]
Correct me if wrong, but I don't see good uses for positive "Offset" ? This only creates "impossible" geometry and often leads to buggy geo.

However, negative values work very well. I'm used to this being called "Inset" in 3DS Max and other tools. Is this maybe a translation thing?

To make this tool more useful and clear to users, I'd suggest

1. Renaming to "Inset"
1. Just use positive values in display, but do the "negative" action. This looks better (neg values can look bad to some users), but functions very well (no bad geometry possible).

**Comment by arthursw** [comment]
Yes, that makes sens.

**Comment by arthursw** [comment]
Ok, I didn't remove the ability to offset, but it creates insets by default. And I renamed to "inset/offset". Closing this for now (I think it's good for the Alpha v2), re-open if necessary.

**Comment by gabrielw-us** [comment]
Perfect! Also, I apologize for being an idiot, "outward" values are of course super useful! Brain must have been half-on when I was testing that :D

**Comment by arthursw** [comment]
It was a good remark. It's true that the resulting geometry might look odd. It was especially true when my algorithm was deleting faces with too many faces per edge. Now it's better
