### ISSUE TITLE
Re-do Translation of Face creates errors

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#142]
**Repro Steps:**
1. New cube
1. face mode > select face
1. move face
1. undo
1. redo

**Result:**
![image](https://cloud.githubusercontent.com/assets/5855470/22314810/2ec44e8a-e331-11e6-9304-eb22fff4574b.png)

**Errors shown in console:**
`Cmd: TRANSACTION REDO
LogEditorTransaction: Redo Transform elements
< Do command: Transform elements - 132
< Destroying a face which is already destroyed.
Error: d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:378: TypeError: Cannot read property 'Edges' of undefined
Error: TypeError: Cannot read property 'Edges' of undefined
Error:     at RemoveVertexFromEdgeCommand.RemoveVertex (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:378:20)
Error:     at RemoveVertexFromEdgeCommand.Do (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:402:14)
Error:     at TransformCommand.ExecuteAtomicCommand (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:67:16)
Error:     at TransformCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:86:22)
Error:     at TransformCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\TransformCommand.js:41:15)
Error:     at TransformCommand.Do (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:98:14)
Error:     at CommandManager.Redo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:129:26)
Error:     at CommandManager.PostRedo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:149:22)
Error:     at ProBuilder_C0.PostRedo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\ProBuilder.js:575:29)`

**Comment by gabrielw-us** [comment]
tested in fresh project, confirmed

**Comment by arthursw** [comment]
Fixed, it was probably the same bug as before.
