### ISSUE TITLE
When moving a PB Object in UE default "Place" mode, collision not updated

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#15]
1) Create new PB Object
2) Switch to Select/Transform PB Mode
3) Switch to UE mode "Place"
4) Move the object- green collision volume left behind

![image](https://cloud.githubusercontent.com/assets/5855470/20066007/226f1a70-a4de-11e6-85b4-b173c4674273.png)

**Comment by arthursw** [comment]
Same as #14
