### ISSUE TITLE
When Edge is selected, "Smooth" checkbox shows incorrect value until toggled

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#150]
If you select an edge, "Smooth" checkbox shows with the dashed lines through- I assume this means "mixed"?

Then, toggle Smooth to either on or off.
Select a different edge, then re-select the first edge- toggle is back to showing dashes.

**Comment by arthursw** [comment]
Fixed, and also improve the 'Smooth group' and 'Mesh group' spin boxes values to warn if selection contains multiple smooth/group values, and to disable those spinbox if there is nothing in selected.
