### ISSUE TITLE
"Intersect Edges" not working

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#153]
I have two edges selected, they share a face, I click "Intersect Edges, but nothing happens and the log shows no errors or warnings?

**Comment by arthursw** [comment]
Maybe the edges already share a vertex? In which case it's normal.

**Comment by arthursw** [comment]
It works fine in my case:

![janv -30-2017 16-01-48](https://cloud.githubusercontent.com/assets/1814799/22427961/78e931c4-e705-11e6-99db-0886f66c3bf3.gif)

I close this for now, tell me if you have something different.

**Comment by gabrielw-us** [comment]
Oohh I see, I totally mis-understood this tool. I'm still not sure how useful it is though, I think other tools (specifically the point-to-point polygon tool) make this obsolete?
