### ISSUE TITLE
"Delete Edges" leaves ghost edges that cannot be selected

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#154]
Tough to describe, but I've made a GIF that hopefully demonstrates this well (below).

As shown in the GIF, those middle edges which no longer have any faces should also be deleted.

![edge-delete](https://cloud.githubusercontent.com/assets/5855470/22398355/9f60719e-e554-11e6-993d-bf30695e1ce2.gif)

**Comment by gabrielw-us** [comment]
Note: same thing happens when deleting faces.

**Comment by arthursw** [comment]
Fixed :)
