### ISSUE TITLE
"Select Edge Ring" only goes one way

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#156]
If you create the object shown in the image below, then select the edge shown, and click "Select Ring", you'll see the Ring only goes counter-clockwise (left).

![image](https://cloud.githubusercontent.com/assets/5855470/22398456/e250c93e-e556-11e6-9e7e-bae6f37d70e4.png)

**Comment by arthursw** [comment]
Fixed :)
