### ISSUE TITLE
"Create Face From Selected Edges" not working with 3 edges selected, other options

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#157]
Create the below cube, and attempt to "Create Face..." from the shown selected edges- nothing happens.

(also note the "ghost edge" per #154 )

In PB-Unity we do this a bit differently, I personally like it better- we have a "Fill Hole" button. So, you select any edge or vert that is on a "hole", and the button will fill it in completely. Or, there is a checkbox to only "Fill" between the selected edges. Works very nicely, especially when a hole has many edges.

![image](https://cloud.githubusercontent.com/assets/5855470/22398525/4a5fc254-e558-11e6-90b9-2c66426103ff.png)

**Comment by arthursw** [comment]
This is not a bug, it's how I made it.

Ok, what I want to do is "select hole" when double clicking on an edge. But we can also have a "Fill hole" button.

Funny thing: you can "intersect edges" and it will create the face. This is not a bug, "intersect edge" calls the intersection algorithm and creates faces from whatever edges link to the selected edges.

This brings the following question: do we provide the auto-intersections (which runs when intersecting edges) by default with ProBuilder? Or would it be an priced plugin?

If auto-intersection is provided by default, we can create a "Fill hole" button which calls it (only with the selected edges/holes).

**Comment by arthursw** [comment]
Select hole button: done!

**Comment by arthursw** [comment]
Select hole on double click: check ! :)

**Comment by gabrielw-us** [comment]
Ah, ok, this is partly a translation thing maybe? Seems like what you call "Intersect Edges", I would call "Fill Hole" :)

Can you explain what "Create Face From Selected Edges" is supposed to do?

**Comment by arthursw** [comment]
No, intersect edges is suppose to intersect selected edges. In fact it call the auto-intersection algorithm. This gathers all surrounding edges, intersect them, and create faces out of them. That is why it behaves like "File hole".

Now "Create Face From Selected Edges" creates face only from selected edges, and won't care about adjacent edges. It's much simpler. It can be preferable to call this method in some cases to avoid creating unwanted faces (as I explained, the auto-intersection algorithm has no good way to know which face to create and which to avoid).

**Comment by gabrielw-us** [comment]
Ah- I'm very confused. When you have time, could you make some images/video showing how these would be used in a real project? I don't fully understand the use or purpose, sorry.

**Comment by arthursw** [comment]
You can learn more about the auto-intersection feature in sketchup : [online demo link](https://my.sketchup.com/app)

The  "Create Face From Selected Edges" is just a regular "Fill hole" feature, provided all edges of the hole are selected (which is easy with a double click).

**Comment by gabrielw-us** [comment]
Sorry, there's a lot there and it's too vague/complex for me to see how it applies to this. When you have time to make an example and show me, I'd really appreciate it.

**Comment by arthursw** [comment]
Ok, we can video chat later for more explanations.

In short, it's not complicated: double click on an edge to select the hole. Click "Create Face From Selected Edge" to fill the hole. In case the mesh needs to be refined, the polygon tool can be used to add details.
