### ISSUE TITLE
"Fill Hole" to replace "Create Face from selection"

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#158]
As noted in #157 , I think this would be a more compact name and function:

Default behaviour:
1. Select an edge or vert on a hole
1. Click "Fill Hole" to fill it entirely with one poly

Or, with "Only Fill Selected" checkbox On :
1. Select several edges or verts on a hole
1. Click "Fill Hole" to create a new poly only between the selected elements

**Comment by arthursw** [comment]
Ok, we could add the second feature, in the Future task - very long term, because it can largely be done with the polygon tool.

**Comment by arthursw** [comment]
For the first feature, see issue #157.

**Comment by gabrielw-us** [comment]
Ah, this is just a mistake I think, having read your other replies in #157  and #153 . Sounds like "Fill Hole already exists, but is called "Intersect Edges"

Is that correct? Sorry! :P

**Comment by arthursw** [comment]
All right!
