### ISSUE TITLE
Error when using Collapse Vertices

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#159]
I've created a simple cube, and attempted to use "Collapse Vertices" on two verts that share an edge.

The vertices appear to collapse, but faces are left as they were and this error log shows:

`Error: d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\ProBuilder.js:828: Error: Asking for an edge with twice the same vertex
Error: Error: Asking for an edge with twice the same vertex
Error:     at ProBuilder_C0.Check (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\ProBuilder.js:828:19)
Error:     at Function.GetEdge (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Edge.js:31:94)
Error:     at Edge.RemoveSimilarEdge (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Edge.js:561:32)
Error:     at Vertex.Replace (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Vertex.js:321:18)
Error:     at Edge.Collapse (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Edge.js:701:26)
Error:     at WeldVertices (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Plugins\VertexActions\VertexActions.js:120:29)
Error:     at Call.global.$execEditor (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\DirectActionCommand.js:23:25)
Error:     at Function.Call (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\DirectActionCommand.js:15:16)`

Image:
![image](https://cloud.githubusercontent.com/assets/5855470/22398625/ad2345da-e55a-11e6-8e75-99a1ac823a44.png)

**Comment by arthursw** [comment]
Fixed :)
