### ISSUE TITLE
Unable to use "Collapse Vertices" on verts that don't share an edge

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#160]
If I select two verts that don't share an edge, "Collapse Verts" will not function. Maybe this is intentional? We allow it in PB-Unity, although it can sometimes create strange geo.

**Comment by arthursw** [comment]
This is not a bug, it would allow crazy geometry and would not be very useful, or ?

Vertex merging are supposed to be done with the polygon tool (which is not finished yet).

**Comment by gabrielw-us** [comment]
I'm not sure how vertex merging would be done with the Polygon tool? We must have very different ideas of what that Polygon tool is- do you have that detailed somewhere?

About Collapsing though, after more thought and some testing in PB-Unity, I agree the geo created isn't worth keeping. So I'm okay with not allowing the collapse if they don't share an edge, but we should throw a warning: "Can Only Collapse Vertices if They Share an Edge"

**Comment by arthursw** [comment]
Ahah, I juste meant that the polygon tool will be used to connect vertices to be able to merge them afterward ;-)

**Comment by arthursw** [comment]
I though the "Can Only Collapse Vertices if They Share an Edge" message was implemented.

**Comment by gabrielw-us** [comment]
Ok, perfect!

**Comment by arthursw** [comment]
Ok, I changed my mind and implemented a Collapse Vertices feature where vertices do not need to be connected.
