### ISSUE TITLE
Negative values on Stair shape should not invert it (edited for clarity)

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#161]

**Comment by arthursw** [comment]
Are you sure it's a good idea? The invert box does the job, and it would "invert the inverted stair" in negative values... 

Maybe the user wants stairs on the roof?

Anyway it's really not a big deal to change.

**Comment by arthursw** [comment]
I think it's good if all shapes behave the same way: inverted only when 'invert' is checked.

**Comment by gabrielw-us** [comment]
Oops, I'm sorry, I was either too lazy to add details, or they got lost.

What I meant was, currently negative values will invert, but that is a bug- negative values should not invert, only the "invert" checkbox should.

So, I think we agree :D

**Comment by arthursw** [comment]
Nice that we agree :-) 

And on my version, the stairs are inverted only when the 'Invert' box is checked, so I think it has been fixed :)

**Comment by gabrielw-us** [comment]
Ok, assigning to myself to check in the next build...

**Comment by arthursw** [comment]
You should be able to test it right now, the C++ side won't directly affect the stairs creation ; and if you feel like it, you can compile the C++ by opening visual studio and pressing 'run' :-)

**Comment by gabrielw-us** [comment]
Oops, I forgot to test this, sorry! Doing now...

**Comment by arthursw** [comment]
Well, stairs is the only shape that I will recreate. It does not work properly now.

**Comment by arthursw** [comment]
I think I will create two shapes "Staires" and "Spiral stairs" for user simplicity sake
.

**Comment by gabrielw-us** [comment]
Oh ok- sounds good, simpler.

**Comment by arthursw** [comment]
Stairs updated :-) not perfect yet, but good enough for the alpha v2 ;-)
