### ISSUE TITLE
Enable both "Thickness + Radius" and "Inner + Outer Radius" for relevant shapes

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#165]
## Shapes Affected:
Cylinder
Tube
Torus
Stairs

## Radius and Thickness
Depending on situation, both the "Inner/Outer Radius" and "Thickness/Radius" methods can be useful. We recently dealt with this in PB-Unity, with very good results:

### Thickness Method:
1. Checkbox for "Use Thickness" which enables "Thickness" and "Radius" value, and hides "Inner/Outer Radius"
1. Positive Thickness value will go outside of "Radius", negative goes inside
1. Radius is positive only, and must be 1 or more
1. If Thickness is negative, it's normalized value cannot be more than (Radius-1)

### Inner/Outer Method
1. When "Use Thickness" checkbox if Off, show "Inner Radius" and "Outer Radius", hide "Thickness" and "Radius"
1. Both Inner and Outer must be positive
1. Outer must always be greater than Inner
1. Inner must always be 1 or greater

I'm hesitantly setting this as AV2 milestone, but if it doesn't make it, that's okay. It would be a major helper for shape creation, though.

**Comment by arthursw** [comment]
Very nice! I don't think it applies to the cylinder, since it does not have thickness, right?

**Comment by gabrielw-us** [comment]
Oops! No cylinder :)

**Comment by arthursw** [comment]
Done :)

**Comment by arthursw** [comment]
I did something slightly different: there is no checkbox to choose between the two methods. Instead the user can modify any of the four parameters (radius, thickness, inner-radius and outer-radius) and others will change accordingly. I could add a checkbox, but I'm not sure if it's necessary. 

In any case, the user must be able to see the resulting inner/outer radius when changing radius/thickness, and vise-versa. 

I think it's simple and efficient as it is now, but we could change in the future if necessary.

**Comment by gabrielw-us** [comment]
Cool, excited to try it out
