### ISSUE TITLE
For AV2, remove "Line" shape option

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#168]
I think let's wait till we have a true Polygon drawing tool, ie #93 / #84 ?

**Comment by arthursw** [comment]
I'll try to upgrade the line tool for the Alpha v2, this is very serious.

**Comment by gabrielw-us** [comment]
I don't see how the line tool is useful, though. From my tests, it's complicated, requires many clicks, and creates very strange/non-useful geo. However, the point-to-point clicking for drawing a poly ie #84 would be much better. If I'm misunderstanding, can you demonstrate how the line tool would be useful?

**Comment by arthursw** [comment]
I improved the polygon tool, I think it nicely merges the cut tool and the line shape features.

The polygon tool will snap on the face / edge / vertex under the mouse, except when the user presses shift: in this case the point is projected on the face / plane the user is currently drawing on.

![polygontool](https://cloud.githubusercontent.com/assets/1814799/23267958/9853d704-f9ec-11e6-94af-324b4dea1222.gif)

**Comment by gabrielw-us** [comment]
Perfect, beautiful! :)
