### ISSUE TITLE
Moving directly from UE "Place Mode" to "PB Mode" with "Create Shape" tool active allows double editing

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#17]
1) Create PB shape
2) Without exiting the "Create Shape" tool, move to UE "Place Mode"
3) Return to "PB Mode"
4) Click and drag on the movement handle- object moves while new shape is created simultaneously 

I suggest switching out of PB Mode should auto-exit "Create Shape Tool".

![image](https://cloud.githubusercontent.com/assets/5855470/20066365/50f7cde6-a4df-11e6-9c73-099fbf20e34e.png)

**Comment by arthursw** [comment]
Yes, perfect! There might be more bugs like this one, we should take care of this.
