### ISSUE TITLE
Changing settings in options (ie, "Grouped" in Extrude) will apply action

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#170]

**Comment by gabrielw-us** [comment]
1. New cube
1. Select face
1. Click Extrude
1. Change a setting- Extrude is applied, and new Extrude becomes active

The following errors also show in the console:

`Error: d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:606: TypeError: Cannot read property '3' of undefined
Error: TypeError: Cannot read property '3' of undefined
Error:     at AddEdgeToFaceCommand.RemoveEdge (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:606:56)
Error:     at AddEdgeToFaceCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:622:14)
Error:     at ExtrudeCommand.ExecuteAtomicCommand (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:70:16)
Error:     at ExtrudeCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:91:22)
Error:     at ExtrudeCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\ExtrudeCommand.js:175:15)
Error:     at ExtrudeCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:101:14)
Error:     at CommandManager.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:118:26)
Error:     at CommandManager.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:138:22)
Error:     at ProBuilder_C8.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\ProBuilder.js:572:29)
Error:     at CancelExtrude.global.$execEditor (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\PBGUI.js:379:35)`

**Comment by arthursw** [comment]
Works for me, I think it has been fixed in previous commits.
