### ISSUE TITLE
Unable to undo Shape creation

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#173]
1. Draw new cube
1. Hit undo - does not work, and errors show up:

`Error: d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:653: TypeError: Cannot read property '3' of undefined
Error: TypeError: Cannot read property '3' of undefined
Error:     at ReplaceEdgeInFaceCommand.ReplaceEdge (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:653:56)
Error:     at ReplaceEdgeInFaceCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\AtomicCommand.js:671:14)
Error:     at ShapeCommand.ExecuteAtomicCommand (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:70:16)
Error:     at ShapeCommand.Execute (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:91:22)
Error:     at ShapeCommand.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\Command.js:101:14)
Error:     at CommandManager.Undo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:118:26)
Error:     at CommandManager.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\Commands\CommandManager.js:138:22)
Error:     at ProBuilder_C19.PostUndo (d:\Unreal Projects\ProBuilderProject_v4\ProBuilder Project\Content\Scripts\js\ProBuilder.js:572:29)`

**Comment by arthursw** [comment]
Yes, I created issue #148 for this bug.
