### ISSUE TITLE
Move/Rotate/Scale handles not showing after creating new object, or clicking on elements

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#18]
1) Create new PB Object
2) Swap to "Select and Transform"
3) Click on Vert, Edge, or Face- move/rotate/scale handles disappear
4) Click back to Object editing- handles still gone

This also happens often after creating a new shape.

To bring the handles back, I have to click around and do various things in the editor, can't figure out the exact steps but somehow they come back eventually.

**Comment by arthursw** [comment]
I am pretty sure it is due to the special keys (shift, alt, command, control) events not firing when it should. I think I know an easy fix: check the state of each special key each frame. I'll do that.

**Comment by gabrielw-us** [comment]
Update from recent screenshare/chat:

1. Handles re-appear after clicking through to "UE Place Mode", then back to "PB Mode"

Should be a simple fix?

2. Handles show on elements if using "ALT + CTRL"

Requiring "ALT + CTRL" to drag-select is default UE behaviour, so that part is fine.
However, click-to-select without dragging should work without using "ALT + CTRL"

I think that sums it up?

**Comment by gabrielw-us** [comment]
*Edited title to be more descriptive/correct

**Comment by gabrielw-us** [comment]
More info that might be helpful:

If I click into an Element mode, when I go back to Object mode, the handles are gone. Only way to get them back is to hold "ALT + CTRL" and drag-select. After doing that, I can once again click (without using ALT + CTRL) to select and manipulate via handles.

**Comment by arthursw** [comment]
Yes, that sums it up, working on it soon!
