### ISSUE TITLE
When drawing new shape, editor often freezes up for significant time

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#19]
1) Start drawing new shape...wait for it- 3/5 times editor will freeze up for 2-10 seconds

**Comment by arthursw** [comment]
Unfortunately, I can't explain this yet, I'll investigate.

**Comment by arthursw** [comment]
This is due to the javascript garbage collection. It was not called frequently enough. Now it is better.

**Comment by arthursw** [comment]
Closing issue for now, reopen if the problem persists.
