### ISSUE TITLE
After swapping to "UE Place Mode", then back to "PB Mode", Face editing options are always shown

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#23]
EDITED: Face always shows, no matter what mode chosen

1. Create PB cube
1. Move to Select/Transform mode
1. Ensure cube is selected, and in **any editing mode other than Face**
1. Swap to "UE Place Mode"
1. Swap to "PB Mode" - note that Face geo actions are now shown, despite being in Object editing mode

![image](https://cloud.githubusercontent.com/assets/5855470/20109843/d979d31e-a5af-11e6-8625-495928dda5c6.png)

**Comment by gabrielw-us** [comment]
Edited to clarify that this also happens for Vert and Edge modes- after swapping in/out of "UE Place Mode", the GUI always shows Face editing options, no matter the actual selected mode

**Comment by arthursw** [comment]
Ok, thanks!

**Comment by arthursw** [comment]
Should be fixed now :)
