### ISSUE TITLE
With two or more PB objects selected, "Merge Meshes" gives "Two or more meshes required..."

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#24]
1. Create pb cube
1. Create another pb cube
1. Select both (move up and down to ensure both selected)
1. Click "Merge" in PB toolbar- error pops up with "Two or more meshes..." etc

![image](https://cloud.githubusercontent.com/assets/5855470/20110580/f5d3d048-a5b2-11e6-9dcb-17c89be239d1.png)

**Comment by arthursw** [comment]
fixed
