### ISSUE TITLE
Using "Alt-Tab" to switch focused applications, results in drag-selection sticking "on"

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#25]
1. Enter "UE Place Mode"
1. Alt-tab to swap focused application, etc
1. Return to Unreal
1. Click in scene- everything is fine
1. Now, swap to "PB Mode"
1. Alt-tab to swap focused application
1. Alt-tab to swap back to Unreal
1. Click in scene- drag selection is stuck on suddenly. A drag-box follows my mouse curser everywhere.

Holding ALT+CTRL and dragging a new selection box temporarily fixes the issue. Moving into "Create Shape" tool also does.

**Comment by arthursw** [comment]
Should be fixed with the last commits. However, in which navigation mode does this happen? With Use UE Navigation mode ?

**Comment by gabrielw-us** [comment]
I'll double check ASAP! :)

**Comment by gabrielw-us** [comment]
Sorry! Lost track of this one.

This does not occur in the "UE Nav Mode", only in the custom mode

**Comment by gabrielw-us** [comment]
Yep, looks fixed!
