### ISSUE TITLE
Remove FBX export, use OBJ instead

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#27]
FBX exporter is taking up a huge amount of space: 1.08GB to be exact. That's a lot of space, especially if someone wants to do per-project installs. Trust me from Unity experience, people will be very unhappy with this.

OBJ export will work just fine, we use it in PB for Unity without issue.

**Comment by arthursw** [comment]
Ok I'll try that, but the best way would be to use UE FBX SDK.

**Comment by arthursw** [comment]
Very nice, I now use the native UE FBXSDK 👍  :-)

**Comment by gabrielw-us** [comment]
Perfect, much better :)
