### ISSUE TITLE
"Convert to Static Mesh" gives "No Smoothing" warning on import

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#28]
1. Create pb shape
1. Select/Transform mode
1. Ensure object is selected, handles show
1. Click "Convert static mesh"
1. Error is shown:

`Warning Warning: No smoothing group information was found in this FBX scene.  Please make sure to enable the 'Export Smoothing Groups' option in the FBX Exporter plug-in before exporting the file.  Even for tools that don't support smoothing groups, the FBX Exporter will generate appropriate smoothing data at export-time so that correct vertex normals can be inferred while importing. `

**Comment by arthursw** [comment]
There is an built-in way to convert ProBuilder meshes to UE static meshes: 

In object mode, select your object, select "Mesh" in the details panel (a child of Root), and under "Procedural Mesh" click "Create Static Mesh".

**Comment by arthursw** [comment]
Closing this for now
