### ISSUE TITLE
"Convert Mesh to Brush" has no effect?

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#30]
Not seeing this do anything- but maybe I'm missing something?

Neat addition, by the way, all these conversion tools :)

**Comment by arthursw** [comment]
Ok, it used to work, I'll fix that.

**Comment by gabrielw-us** [comment]
Actually, can we move the conversion tools all into "Future Tasks", and hide/remove them from Alpha V2? I'd rather concentrate/spend time on the core features.

**Comment by arthursw** [comment]
Ok I removed this feature because of a link error on windows (it could work fine on OS X)
