### ISSUE TITLE
Hitting "Undo" after "Regenerate Shape" removes the object

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#32]
1. Create pb shape
1. Edit elements on shape, so that "Regen Shape" button shows
1. Click "Regen"
1. Hit "Undo" - shape disapears

Note: hitting "Undo" a second time brings back the object, pre-regen. However, this will confuse users.

**Comment by arthursw** [comment]
Yep
