### ISSUE TITLE
Several "Element Editing" items showing up in Object editing mode

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#34]
See image:

![image](https://cloud.githubusercontent.com/assets/5855470/20112208/70ada90a-a5b9-11e6-91f7-e3961185cee2.png)

**Comment by arthursw** [comment]
Yes, this is normal, buttons in the circle correspond to the _selection tab_. 

When I will improve the GUI, I will create bigger margins, maybe borders around each tabs: Object, Face, Edge, Vertex, Selection, UV and Settings tabs.

**Comment by gabrielw-us** [comment]
Oh, I see. However, these are all geometry actions, so I think they should only show when in a geometry-editing mode. Otherwise they are taking up space in the GUI without being useable?

**Comment by arthursw** [comment]
Ah yes, of course, I didn't realize this!

**Comment by arthursw** [comment]
fixed
