### ISSUE TITLE
Extruding 2 faces at once (with SHIFT + move) breaks PB

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#37]
Each time I extrude 2 or more faces at once, using shift + drag, either the mesh breaks or the the mesh becomes unselectable, or other issues. Seems somewhat random, but does always break.

**Comment by arthursw** [comment]
Ok, this happens when you have `Intersect with parallel faces` checked. 

When you extrude two neighbour faces with this option checked, without `Extrude by group` it creates two separate extrusions. Then it tries to intersect new faces.

**Comment by arthursw** [comment]
I'm working on it!

**Comment by arthursw** [comment]
now, when extruding faces with a common edge in one direction there is a warning message saying "One or more face might have been created inside the mesh. You might want to use 'Extrude by group' to extrude multiple faces together."
