### ISSUE TITLE
Using SHIFT + Rotate on a face breaks mesh

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#38]
1. Create cube
2. Select face and hold SHIFT while rotating

Mesh goes invisible and undo does not fix

**Comment by arthursw** [comment]
I'm working on it!

**Comment by arthursw** [comment]
Fixed: invalid faces could not be triangulated and were complaining. Now they fail triangulating silently, and are triangulated as soon as they can.
