### ISSUE TITLE
Selection broken after Extrude via GUI button

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#42]
Select a face, click Extrude, then click Validate
No longer able to select Faces

**Comment by arthursw** [comment]
This does not happen on my version. 

The issue might be solved, or it's different on windows (very unlikely), or maybe I didn't do the exact same steps to reproduce the issue. 


Can you tell me more about that, and give me the output of the Javascript console window (find it in menu `Window > Developer Tools > Javascript Console`)

**Comment by gabrielw-us** [comment]
Sure, I'll check it again, and get details

**Comment by gabrielw-us** [comment]
Yep, looks fine now
