### ISSUE TITLE
If face is manipulated (move, etc) after clicking Offset, cannot fully Cancel

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#44]
1. Select face
1. Click Offset
1. Move face
1. Click cancel- green line remains

I would suggest we completely lock editing until the Offset is finished (Validate or Cancel) ?

![image](https://cloud.githubusercontent.com/assets/5855470/21295714/1be2eee6-c529-11e6-9b7c-312895a8c0c9.png)

**Comment by gabrielw-us** [comment]
Update: similar issue with Extrude. I'd suggest maybe:

A- Lock selection and editing until hit Validate or Cancel
B- or, Auto-Cancel if selection changed or manipulated?

Personally, I'd prefer the "Lock" method. Seems less chance of bad stuff happening.
There'll also need to be some sort of auto-cancel regardless, though, for things like swapping to other modes, etc.

**Comment by arthursw** [comment]
Fixed: 
- disable other GUI elements when extruding/offsetting from GUI
- auto-validates when changing mode (my 3D artist colleague told me it's better to auto-validate than auto-cancel, but this can be modified.)

**Comment by gabrielw-us** [comment]
Good point- thanks!
