### ISSUE TITLE
Strange selection overlay after Undo - EDIT: also after other actions

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#45]
Seeing this strange overlay on selected face after Undoing, sometimes (image below)

Specifically, after Undo the "Invert Face" command

![image](https://cloud.githubusercontent.com/assets/5855470/21295783/90838570-c52a-11e6-9980-2c63271b14ec.png)

**Comment by gabrielw-us** [comment]
Note: also seeing this after using "Flip Triangle Faces" :

![image](https://cloud.githubusercontent.com/assets/5855470/21295844/9baf0266-c52b-11e6-847c-b3b2766fdaef.png)

**Comment by gabrielw-us** [comment]
Same for "Merge Faces"

**Comment by arthursw** [comment]
This is because I didn't to update the selection highlights (the vertex colors) after Undo/Redo and when the selection changes.

I fixed this where you noticed it, but there might remain some cases I didn't see...
