### ISSUE TITLE
ALT-TAB with face selected breaks selection and movement

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#48]
1. Select a Face
1. Swap to other program
1. Swap back- cannot select elements or move camera

Probably related to #25 , but different bug now

**Comment by arthursw** [comment]
this doesn't happen on mac. I'll check on windows later.

**Comment by gabrielw-us** [comment]
Noticed this is still happening, and it only happens when "UE Navigation" is off, so it's an issue with the custom navigation, perhaps?

**Comment by arthursw** [comment]
Ok, this should be solved by now, closing for now. To double checked ;)

**Comment by gabrielw-us** [comment]
Looks good!
