### ISSUE TITLE
Object outline not updated after deleting faces

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#49]
1. Create cube
1. Delete enough faces to change the cube's shape/outline

Outline remains the same:
![image](https://cloud.githubusercontent.com/assets/5855470/21295965/282b5256-c52e-11e6-99e9-20faaae23372.png)

**Comment by arthursw** [comment]
This is the normal behaviour. 

Edges are not deleted when you delete a face. And vertices are not deleted when you delete an edge.

However, face are deleted when you delete edges, and edges are deleted when you delete vertices.
