### ISSUE TITLE
View controls should not change when entering PB Edit mode

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#5]
I understand the idea of this, it could be an option, but should not be default. New users will quickly be confused/angry when their view controls suddenly change.

Also, most users won't be using PB for "modeling" in the Max/May/Blender sense, and so will not want the "orbital" view controls. They'll be building level geometry, and will prefer to stick with Unreal's standard view controls.

**Comment by arthursw** [comment]
Ok

**Comment by arthursw** [comment]
Ok, settings are not saved/loaded, so it will be just as the user want it to be.
