### ISSUE TITLE
Extruding faces creates extra geometry if all edges are open

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#50]
1. Create Cube
1. Select all except 1 face, Delete
1. Select remaining face, Extrude

Extra face is created, capping the back of the shape

**Comment by gabrielw-us** [comment]
Oops, here's the image:
![image](https://cloud.githubusercontent.com/assets/5855470/21296004/16c40426-c52f-11e6-8bed-885fb2d371d9.png)

**Comment by arthursw** [comment]
This is a normal behaviour (for now) when "Intersect with parallel faces" is checked:
- the edges where not deleted when you deleted faces
- after extrusion, the auto-intersection algorithm merge edges and creates faces where it can

I can change the behaviour to avoid the extrude tool to create faces with edges which didn't belong to a face.

If "Intersect with parallel faces" is unchecked, the edges will not be merged, meaning you will have the previous edge overlapping the new edges. And no new faces will be created.
