### ISSUE TITLE
Edges are thin or invisible

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#51]
Even with "thick edges" on, edges are often invisible, or very hard to see, especially as the object gets further from the camera.

Screen-space edge rendering would be better, vs the current (I assume?) world-space edge rendering.

![image](https://cloud.githubusercontent.com/assets/5855470/21297446/5a729420-c54e-11e6-9ede-fd09d4f3c140.png)

**Comment by arthursw** [comment]
The checkbox name is not good.

Edges are rendered in screen-space when "Thick edge" is unchecked (by default), and in world-space when it's checked. 

Edge highlight color should be the same in both modes. I'll change that.
