### ISSUE TITLE
Selected Edge line stays in place after moving

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#53]
![image](https://cloud.githubusercontent.com/assets/5855470/21297461/fc9759b6-c54e-11e6-9cd6-d60427fb5cb3.png)

**Comment by arthursw** [comment]
Again, this doesn't happen on my version, I'll try on windows later.

**Comment by gabrielw-us** [comment]
Interesting. Let me know how that test goes.

**Comment by arthursw** [comment]
fixed
