### ISSUE TITLE
After using "Create Face from Selected Edges", unable to Ring or Loop

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#56]
1. Create Cube
1. Select a face, extrude it a bit, just to create a loop
1. Verify that Select Ring and Select Loop works (they do, at this point)
1. Select the extruded face, and delete it
1. Select the new open edges, and use "Create Face from Selected Edges" to fix the hole
1. Attempt to Select Ring or Select Loop again- this time, it does not work

**Comment by arthursw** [comment]
Strange, this does not happen for me : /

**Comment by gabrielw-us** [comment]
I'll re-test in the next version, maybe it's an old issue

**Comment by gabrielw-us** [comment]
Yep, looks good now!
