### ISSUE TITLE
Shape Parameters: Default Width/etc should be more than 0

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#59]
Currently, using the (handy) "Reset" button results in an impossible shape

**Comment by arthursw** [comment]
This does not happen on my version. You probably have an error. Can you check the Javascript console please ?

**Comment by gabrielw-us** [comment]
Yep, will do!

**Comment by gabrielw-us** [comment]
Hmm, I don't see any errors popping up at all. When  I hit the Reset button, the value goes to zero, but the shape does not actually change.

**Comment by gabrielw-us** [comment]
![reset to zero](https://cloud.githubusercontent.com/assets/5855470/21529380/0e91ac60-cd07-11e6-976f-fc14898d9425.gif)

**Comment by arthursw** [comment]
Ah ok I didn't understand the issue, sorry ;-) I'll fix that

**Comment by arthursw** [comment]
Ok fixed. I Noticed that when reseting to default, the OnChange callback is not called. 

So the shape does not update until the user hit enter with the value selected. 

I think it's more a UE bug...

**Comment by gabrielw-us** [comment]
Ah, good catch! So it won't allow zero anymore, right?
