### ISSUE TITLE
If element (face/edge/vert) is selected, then swap to Create Shape, panel is broken

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#60]
1. Create cube
1. Select face
1. Without de-selecting or any other action, click on "Create Shape"

![image](https://cloud.githubusercontent.com/assets/5855470/21297872/cd53a9aa-c555-11e6-82be-7673cf928228.png)

**Comment by arthursw** [comment]
fixed!
