### ISSUE TITLE
Edges can be very hard (or impossible) to select

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#63]
I'm noticing some edges, depending on angle and distance from camera I think, are very hard to select. For instance, the below GIF, one edge is impossible to select, while others select fairly easily:

**Comment by arthursw** [comment]
Did you forget to upload the gif?

**Comment by gabrielw-us** [comment]
Oops, here it is :)

![edge select tough](https://cloud.githubusercontent.com/assets/5855470/21594546/b8852006-d0f1-11e6-9ad5-0e89c7f60ed1.gif)

**Comment by arthursw** [comment]
Ok I think I fixed it and closed the issue.
