### ISSUE TITLE
Selecting faces occasionally gets wrong face

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#65]
I'm not able to pin this down to an exact repro, but often selecting faces by clicking next to an edge will cause the wrong face to be selected. See the GIF below for examples.

![face select wrong](https://cloud.githubusercontent.com/assets/5855470/21530913/237a88bc-cd12-11e6-8bf8-a15658f5ae1c.gif)

**Comment by arthursw** [comment]
Ok, it seems this was due to an imprecision of UE, fixed.
