### ISSUE TITLE
If "Extrude By Group" is on, don't show "Extra faces created..." warning

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#66]
Since it's extruding as a group, no extra faces should be created, right?

**Comment by arthursw** [comment]
Strange, this message should not appear. I could not reproduce it (didn't try a lot). Can you send me a gif please? Thx!

**Comment by gabrielw-us** [comment]
Yep, will do- assigning over to myself so I remember to get that for you.

**Comment by gabrielw-us** [comment]
Check!
