### ISSUE TITLE
Extrude adjacent with quads (see images)

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#68]
EDIT: I see now, your method removes the bad geometry for users who aren't paying attention...I'm not sure it's best to do things without the user knowing, but I see the benefit.

Changing this to a "question", and we'll see where it goes :)

---

Currently, if I extrude adjacent faces on a single axis, I get this:

![image](https://cloud.githubusercontent.com/assets/5855470/21531130/b21afb46-cd13-11e6-8aeb-9981087c6c50.png)

vs nice quads:

![image](https://cloud.githubusercontent.com/assets/5855470/21531168/e9352e58-cd13-11e6-8853-22402b61c1ba.png)

**Comment by gabrielw-us** [comment]
I think there are good intentions here (and it's well done), but it's dangerous to start doing automatic things without asking users. New users start expecting "auto-magic" fixes for all their geo mistakes, and experienced users get annoyed at things happening that they didn't ask for.

**Comment by arthursw** [comment]
Well, again, this happens because "Intersect with parallel faces" is checked.

This checkbox could be unchecked by default, but anyway, users should really understand what a valid mesh is, and how to manipulate it correctly. 

The question is "How to explain it correctly to new users". I'm not sure how.

**Comment by gabrielw-us** [comment]
Okay, I've marked this for myself to dig into more, thanks! :)

**Comment by arthursw** [comment]
I close this for now, please re-open if necessary.
