### ISSUE TITLE
Ability to supply details for the "Subdivide Faces" function?

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#69]
Often, I only want to add divisions along one axis. Seems like no way to do this right now?

Apologies if I'm doing this wrong, I haven't used Git much.

**Comment by gabrielw-us** [comment]
It's not available  yet, but we'll be adding something similar to "Connect Edges" from PB-Unity:
http://procore3d.github.io/probuilder2/toolbar/edge/#connect-edges

**Comment by gabrielw-us** [comment]
Yep, there's a ton of ways to do this, all seperate tools really. Current is good for a quick right-down-the-middle cut.

In Max, I really liked that you could select any amount of edges, pop open the "Connect" tool, and choose how many new edges, distribution, etc. Really slick for adding detail.

There was also a tool to click point-to-point and "draw" new edges in, which was equally great, for dif situations.

If you have time, it'd be great to see specific feature requests posts for individual tools like this. GIFs like that and references to other tools are great too.

**Comment by arthursw** [comment]
Ok, so the line tool is already quite powerful, it enables to quickly split a face from middle points:

![janv -03-2017 14-08-13](https://cloud.githubusercontent.com/assets/1814799/21608646/1f333866-d1be-11e6-8afb-7fda3466efc8.gif)

I will improve it to be able to add more points at each click. There are others things to improve with the line tool (intersections, and snap).

I think we also need a slice plane feature, so let's make a feature request.

**Comment by arthursw** [comment]
So I think the line tool does a good job toward this goal. In addition we already have the connect selected vertices. I also added a [connect selected edges](https://github.com/gabrielw-us/ProBuilder-Unreal-Public-Tracker/issues/107) issue / feature request. I close this for now, re-open if necessary.
