### ISSUE TITLE
Deleting a shape crashes Unreal

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#7]
Steps:

1) Create shape (I used a cube)
2) Select Shape (object mode)
3) Hit "Delete" on keyboard

Unreal crashes.

**Comment by arthursw** [comment]
This works fine on my computer, maybe I fixed this bug, does it still occur?

**Comment by gabrielw-us** [comment]
Seems fixed!
