### ISSUE TITLE
Expanding on UE4's "clone drag" - Use "ALT" instead of "SHIFT" for clone-type actions

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#70]
Alt+drag in UE4 clones objects. It would be extremely great if this worked in Probuilder for various operations: clone-drag a face to extrude it, for instance (Source 2's Hammer does this).

**Comment by gabrielw-us** [comment]
Good point! Since ALT is Unreal's default for "duplicate", makes sense to use this instead of SHIFT.

@arthursw , any technical/other issues you see here?

**Comment by gabrielw-us** [comment]
Also @joewintergreen - feel free to set the "Label" and "Assignees", that helps keep things organized. You can Assign to both Arthur and myself for most things, or just Arthur if it's a purely technical thing, but that's not a big deal, the Label is most important. Thanks!!

**Comment by joewintergreen** [comment]
I couldn't figure out how to assign labels 😅

**Comment by gabrielw-us** [comment]
Made some wee tweaks to the title for clarification, if you don't mind 😁

**Comment by joewintergreen** [comment]
I actually like the current shift-drag extrude feature - the only difference I'd want for alt-drag is that the camera shouldn't follow the extruded face. The camera following the extruded face is a cool extra thing, but seems separate from what I'd want as base drag-extrude functionality.

**Comment by joewintergreen** [comment]
like seriously how do i edit this what's wrong with me
![image](https://cloud.githubusercontent.com/assets/7104380/21538765/7019aa3a-cdf4-11e6-910d-5976e78237ed.png)

**Comment by gabrielw-us** [comment]
Yep, only change here would be the key used- ALT instead of SHIFT.

I think SHIFT does that follow cam simply because SHIFT is Unreal's follow cam hotkey, so that would remain if the user also held SHIFT while ALT dragging :)

**Comment by gabrielw-us** [comment]
EDIT: ah, shite, maybe the system doesn't let you set labels? Hmm, I'll look into that, sorry!

**Comment by joewintergreen** [comment]
Oh, interesting! I assumed it was something you did on purpose. Pretty cool!

**Comment by arthursw** [comment]
I had to do a hack, but it's done.
