### ISSUE TITLE
I, a true rebel, question the need for a widget/pivot in this tool.

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#74]
Feel free to file under "too wild, too revolutionary, too gosh-darned crazy" but:

I'm generally against the idea of having a widget for most geometry editing. It's one thing for moving individual static objects - actors, static meshes - that's more or less fine - but for modeling, I think it's a bad UX paradigm. 

Widgets move around in relation to the object and have to be manually re-centered or moved, they're a fiddly small target to grab, and they inherently necessitate multiple modes. With widgets, no matter how much screenspace is occupied by the thing you're trying to operate on, the widget you need to click is a tiny, arbitrarily-positioned thing. Take a look at things like Hammer (no widget) and see how much you think you can get away with without using that particular interface paradigm, and I reckon you might be surprised. As a related thing, the widget in PB gets itself into some unfortunate situations (much like the UE4 csg widget). Like, it's positioned somewhat sensibly when you create an object, but then you edit the object and now it's somewhere totally arbitrary and "widget management" just became a new repetitive task in your core loop.

One approach to this (although it doesn't go far enough for me) would be to always center the widget more-or-less under the cursor - using it would still only affect the selected object, but you'd solve the "widget in a weird position" issue. 

A better paradigm, I reckon, is marquee selection and editing. Drag the corners of a thing to make it do a thing. Again, see Hammer. Just spitballin'!

At minimum, the object's widget should aggressively re-center all the time.

**Comment by gabrielw-us** [comment]
Can you post a vid/gif of how you'd imagine it working, and/or how it does in Hammer? I've forgotten :P

**Comment by joewintergreen** [comment]
[This vid shows it off a bit.](https://www.youtube.com/watch?v=xOBEy-zIotE)

**Comment by gabrielw-us** [comment]
Ah, I see! I did enjoy that in Hammer. However, I don't see how it would translate over to complex 3D models. Brush-based stuff, certainly, but when you want to build a complex shape as a single mesh (vs multiple brushes), you need that widget. Unless I'm missing something here?

**Comment by arthursw** [comment]
Wooow this video is amazing!!! Thank you 👍 

I just hope nobody will watch it, because it will rise an army of ProBuilder competitors!

I can't agree more with you, we need to be able to drag basic shapes by corners/midpoints, and the measurements should appear near the edges. I will implement this feature. 

This could be extended to general object manipulation: using the bounding box as a way to scale/transform the object.

However, I think the gizmo will still be required for fine vertex manipulation.

So this is a nice feature request!

**Comment by gabrielw-us** [comment]
Something else @joewintergreen and @arthursw - we could use the arrow keys for input while a 2D view is selected active, perhaps? If a key press moved the selected elements by grid amount, that would would work nicely.

**Comment by arthursw** [comment]
Ok, that would be nice, let's make it a new feature request!

**Comment by joewintergreen** [comment]
Also thanks Arthur, here's the sequel to that video. https://www.youtube.com/watch?v=6ubu76gEvM8&t=2s

**Comment by arthursw** [comment]
Arf, very nice video again! I fully agree again :-) 

But.. I'm afraid that this will encourage new competitors! I'm not very confortable with this.

ProBuilder should solve the problems you mentioned in the video. Especially if we follow your advices :-)

I hope the UE team is far from releasing their new geometry tool (but I think they will release it too soon : / ).

**Comment by joewintergreen** [comment]
I've heard good things, but I'm sure they'll take ages. 
My videos have both been up for a long time, so I don't think there's too much to worry about :P Just keep doing your best!

**Comment by arthursw** [comment]
Thanks :)

**Comment by gabrielw-us** [comment]
Good to see things moving here! I'm going to create individual, focused feature requests for the items here...this post is a good wide-view, but need specifics. Will post links in a sec...please comment on those if I get anything wrong :)

**Comment by gabrielw-us** [comment]
Okay @joewintergreen and @arthursw , I've created specific feature requests:

#88 and #87 

Those two seemed the core ideas. Let me know if I missed something.

**Comment by arthursw** [comment]
Ok, since this issue has been split into two issues, I close it.
