### ISSUE TITLE
On "Create Shape", speed things up by inferring the missing dimension

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#76]
Creating a shape could (and should!) be made faster by not necessarily requiring you to drag out height - you're dragging out a shape on X and Y, but it's usually safe (and helpful) to infer the Z dimension from that of the last shape you had selected. My suggestion would be: 

-as you drag out the shape on X and Y, its height is the Z of the last selected object

-after that drag, the Z height stays the same, but if you move the mouse *significantly* one way or the other, it snaps to the cursor and resumes the current behavior. If you're okay with the assumed height, you can just click once more to keep it.

**Comment by gabrielw-us** [comment]
Problem is, the second corner can get occluded by the shape, while still drawing the first level, making it hard to tell where your base is.

**Comment by joewintergreen** [comment]
That'd be solved by still drawing wireframe for the occluded edges/verts.

**Comment by gabrielw-us** [comment]
Hmm. I'm down with drawing the entire object as wireframe until it's been completed. Sounds good.
@arthursw , thoughts?

**Comment by arthursw** [comment]
The current system remembers the height of the last created shape, it's pretty simple and close to what you want. I think it's good now.

Now, on the long term, it would be nice to make it as in Sketchup: when you move your cursor over a face while extruding/creating a shape, it adjust the size to reach the same plane, which is extremely handy.

![janv -02-2017 21-09-01](https://cloud.githubusercontent.com/assets/1814799/21595586/c7a33b98-d12f-11e6-9b23-e38d16bfb90d.gif)

**Comment by arthursw** [comment]
you can try it: https://my.sketchup.com/app

**Comment by gabrielw-us** [comment]
Yes, perfect @arthursw ! Maybe require a keyboard modifier though, like "V" in Unity snaps to anything beneath the mouse curser.

**Comment by arthursw** [comment]
Ok I close this issue and create another one for the "snap to face under cursor" one.
