### ISSUE TITLE
Can't "Create Shape" while in UE4 navigation style?

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#80]
What it says on the tin.

**Comment by gabrielw-us** [comment]
Ah, that's Unreal being wonky. Hold "ALT + CONTROL" so the drag works.

Actually, we could probably force it to just use left-click, no modifiers required, right @arthursw ?

**Comment by arthursw** [comment]
That's possible, but then it's not the "UE nav style" anymore.

We could rename this checkbox...

**Comment by joewintergreen** [comment]
It sounds like an okay solution to me. I only ever use WASD and right click
to move around in UE4 really.

**Comment by joewintergreen** [comment]
You'd still be able to move with WASD. I don't think most people use left
click to move.

**Comment by gabrielw-us** [comment]
By UE default, when the left mouse click "does something", navigation is ignored.

For example, left click in the scene and move mouse- you move around
However, if you left-click on a gizmo and move the mouse, the gizmo action is applied, and you do not move

I think it would make sense for this to apply with shape creation- creating the shape is an "Action", so you when you left-click (anywhere), while in Shape Create mode, navigation is ignored. The action "consumes" the navigation. That seems to follow default UE scheme.

I still think it's weird as hell, but when in Rome... :D

**Comment by gabrielw-us** [comment]
Edit @joewintergreen : oh yeah, WSADing with left-click is 76% worthless. I would only ever use right-click WSADing.

How does this sound @arthursw ? Summery: in Shape Mode, ignore left click nav, just do the action (drawing shape, selection, etc)

**Comment by joewintergreen** [comment]
That would work for me.

*Joe Wintergreen*
*Director*
*Impromptu Games* <http://impromptugames.com/>
*facebook <http://www.facebook.com/ImpromptuGames> twitter
<https://twitter.com/joewintergreen> linkedin
<http://au.linkedin.com/in/joewintergreenarthur>*

**Comment by arthursw** [comment]
Ok, it's now possible to create shapes with left click in 'UE navigation mode'.
