### ISSUE TITLE
Some kind of "additive bevel" would be an amazing tool.

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#81]
I haven't seen bevel in probuilder at all yet, but putting that aside...

I'd love to be able to mass-bevel surfaces without it affecting my ability to design that environment by actually adding complexity to the models. Look at something like Dishonored 2 (and I have no idea what their geo tools are, but they're powerful and it's not just modular meshes) - every wall edge is pretty much bevelled, not always uniformly. But traditionally, doing that makes it way more annoying to go back and make macro-level changes to the map later on. I basically want to be able to select all the edges in a room, bevel them slightly, and then every time I move an edge or vert around, it un-bevels and then re-bevels at the end of my drag if it still makes mathematical sense to bevel. 

I guess what I'm describing might be like modifiers in Max.

**Comment by gabrielw-us** [comment]
Yep, modifiers in Max are great. Suuuuper complex though. Creating a special "Pie in the Sky" label for things like this- not a bad label, just means "sure, that'd be great, but it's unlikely to happen soon/be feasible". These are good to have though, don't hold back!

**Comment by arthursw** [comment]
+1

**Comment by arthursw** [comment]
Ok, I created issues [105](https://github.com/gabrielw-us/ProBuilder-Unreal-Public-Tracker/issues/105) (chamfer) and [103](https://github.com/gabrielw-us/ProBuilder-Unreal-Public-Tracker/issues/103) (modifiers).
