### ISSUE TITLE
Option for "Select Occluded Elements When Drag-Selecting: ON/OFF"

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#83]
Often that's what you want, but often it's not. Needs a toggle.

**Comment by gabrielw-us** [comment]
Yep, I assume that's on @arthursw 's mental list, good to have it written down too. Thanks!

Marking "Accepted", not sure if it will be part of the public release though.

**Comment by arthursw** [comment]
It's already there: in settings: the "Select hidden" checkbox.

**Comment by arthursw** [comment]
Or I misunderstood?

**Comment by joewintergreen** [comment]
Oh, cool. In that case it just needs to be more visible somewhere. I
imagine there's a big UI pass waiting to happen later to bring the UI more
in line with Unity PB?

Although I'm sure improvements can be made vs Unity's.

**Comment by gabrielw-us** [comment]
Yep, UI has lots to be figured out :)
