### ISSUE TITLE
Cut Tool that operates point-to-point on click

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#84]
Proper Feature Request from #69 

A cut tool that works similar to how 3DS Max works, if anyone is familiar with this:

1. Click "Start Cut"
1. Click anywhere on the mesh (if face or edge, insert new vert at click point)
1. Click second point- new edge is drawn from first point, to this one
1. Click another point- new edge, etc
1. Hit "ESC" /right-click/etc to exit Cut

Arthur and I also discussed snapping the cut to the grid, when possible to do without pushing the new vert in/out of the face.

How does that sound?

**Comment by arthursw** [comment]
Did you try the line tool? It's far from perfect, but when it will be finished and polished it will be the mesh you require. 

_Side note: Shortcuts: 'L' for the line tool, 'M' for the rectangle tool._

**Comment by gabrielw-us** [comment]
Ah, I see- it's in the Create Shape portion right now. My thoughts:

1. I think it would be better placed in the Edit tools
1. A point-to-point continuous method (see original post) would be ideal for me

**Comment by gabrielw-us** [comment]
Oof, it's really easy to create mad geo with that- impressed that it doesn't crash! :)
![image](https://cloud.githubusercontent.com/assets/5855470/21753328/061e7670-d5b9-11e6-8fca-2e98de382205.png)

Locking the cuts to the mesh should at least make it harder to create terrible geo like that.

**Comment by arthursw** [comment]
Ok, the polygon and the clip tools should correspond to this feature. I close this for now, please re-open it if I forgot something.
