### ISSUE TITLE
Source 2 Hammer: Things To Be Learned

### ISSUE THREAD

**Issue by joewintergreen** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#86]
This isn't an issue as much as a video I recorded because I thought ya'll could benefit from it. 

Source 2 has a new version of Hammer with a bunch of cool features. They moved from BSP to making-meshes-in-the-editor but kept a lot of what made working with Hammer fast and great. I'd say Source 2 Hammer is probably the best level editor out there right now. Don't worry though, you can't make games with it. ¯\_(ツ)_/¯

[Video!](http://impromptugames.com/ue4/sharex/hammer2.mp4) Discuss.

**Comment by arthursw** [comment]
Ok, nothing very new here. I planned to do the line tool this way. 

I have better level-design oriented features in mind. 

Like a house tool, maybe a tunnel tool. But this is in a far future.

**Comment by arthursw** [comment]
You can also try [Vectary](https://www.vectary.com/engine/). It has nice UI and features.

**Comment by joewintergreen** [comment]
I would really really want the clip tool, the bridging with interpolated sections, the polygon-drawing tool, and the displacement-tools-on-any-subdivided-surface aspects to be in Probuilder. Source 2 Hammer, which I basically just started using, is, I think, the best editor or modelling tool I've ever tried.

**Comment by arthursw** [comment]
Yes, it's all in the todo list!

**Comment by gabrielw-us** [comment]
Ah, some real magic in Source 2!

Clip tool, poly drawing tool, and displacement tools are the most feasible and useful items I saw, yep. (other than the basic stuff).

**Comment by arthursw** [comment]
Ok I close this issue. An issue / feature request should be opened for: clip tool, the bridging with interpolated sections, the polygon-drawing tool, and the displacement-tools-on-any-subdivided-surface

**Comment by arthursw** [comment]
ok I created the issues.
