### ISSUE TITLE
Thought: remove all Material and UV controls for Alpha V2 public release?

### ISSUE THREAD

**Issue by gabrielw-us** [gabrielw-us/ProBuilder-Unreal-Public-Tracker#89]
Since the modular plugin system makes this possible, this might be good to do.

Seems best to focus on one area at a time, get each right, then move on.

Also, there's just so much to do for Texturing stuff, it will delay Alpha V2 too far. Better to just get geo editing and shape creation top-notch, then make Alpha V3 the Texturing update?

**Comment by arthursw** [comment]
Ok, I'll focus on non UV/material things first!
